"""added relationship b/w orders and suppliers

Revision ID: 233da7c41d9a
Revises: e4dfcdc005ca
Create Date: 2026-03-11 22:58:32.217344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233da7c41d9a'
down_revision: Union[str, Sequence[str], None] = 'e4dfcdc005ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
