"""supplier rating 2

Revision ID: 5d8a0a317de2
Revises: 5d680fae59a1
Create Date: 2026-03-14 12:59:33.248620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8a0a317de2'
down_revision: Union[str, Sequence[str], None] = '5d680fae59a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')
    # ### end Alembic commands ###
