"""removed complaint column

Revision ID: 810522b0d857
Revises: 097b0214f8ee
Create Date: 2026-03-09 19:37:10.632641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810522b0d857'
down_revision: Union[str, Sequence[str], None] = '097b0214f8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'complaint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('complaint', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
