"""added complaint column to complaint model

Revision ID: e4dfcdc005ca
Revises: 810522b0d857
Create Date: 2026-03-10 18:06:05.129922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dfcdc005ca'
down_revision: Union[str, Sequence[str], None] = '810522b0d857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('complaint', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'complaint')
    # ### end Alembic commands ###
