"""added relationship b/w orders and suppliers 2

Revision ID: fd73f67e70cb
Revises: 233da7c41d9a
Create Date: 2026-03-11 23:00:40.966062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd73f67e70cb'
down_revision: Union[str, Sequence[str], None] = '233da7c41d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'supplier_id')
    # ### end Alembic commands ###
