from enum import Enum

class OrderStatus(str,Enum):
    PENDING="PENDING"
    ACCEPTED="ACCEPTED"
    PACKED="PACKED"
    SHIPPED="SHIPPED"
    OUT_FOR_DELIVERY="OUT_FOR_DELIVERY"
    DELIVERED="DELIVERED"
    CANCELLED="CANCELLED"